<a href="https://colab.research.google.com/github/alexserxio/sem_2/blob/main/%D0%BB%D0%B0%D0%B1%D0%B02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


size = 10
x = np.zeros((size, size), int)


for i in range(size):
    x[:, i][i:] = np.arange(i + 1, size + 1)


print(x)


[[ 1  0  0  0  0  0  0  0  0  0]
 [ 2  2  0  0  0  0  0  0  0  0]
 [ 3  3  3  0  0  0  0  0  0  0]
 [ 4  4  4  4  0  0  0  0  0  0]
 [ 5  5  5  5  5  0  0  0  0  0]
 [ 6  6  6  6  6  6  0  0  0  0]
 [ 7  7  7  7  7  7  7  0  0  0]
 [ 8  8  8  8  8  8  8  8  0  0]
 [ 9  9  9  9  9  9  9  9  9  0]
 [10 10 10 10 10 10 10 10 10 10]]


In [ ]:
import numpy as np


# Исходные данные
R1 = 15
R2 = 15
R3 = 15
R4 = 10
R5 = 15
R6 = 25
E1 = 80
E2 = 105
E3 = 130
# Задаем матрицу линейных коэффициентов
matrix = np.array(
    [
        [1, 0, -1, 0, 1, 0],
        [0, 0, 0, 1, -1, -1],
        [-1, -1, 0, 0, 0, 1],
        [-R5, 0, 0, 0, R6, -R4],
        [0, 0, -R1, -R3, -R6, 0],
        [0, -R2, 0, -R3, 0, -R4],
    ],
    dtype=float,
)
# Задаем ответы для линейных уравнений
answers = np.array([0, 0, 0, -E1, E3, E3 + E2 - E1], dtype=float)


# Решаем СЛАУ с помощью библиотеки numpy
print(
    "Решение, полученное с помощью библиотеки numpy\n", np.linalg.solve(matrix, answers)
)


def make_diagonal_dominant(matrix):
    for current_row in range(len(matrix)):
        max_element = max(matrix[:, current_row][current_row:])
        max_row_index = (
            np.where(np.isclose(matrix[:, current_row][current_row:], max_element))[0][
                0
            ]
            + current_row
        )
        if current_row != max_row_index:
            matrix[[current_row, max_row_index]] = matrix[[max_row_index, current_row]]


def remove_zeros_from_diagonal(matrix):
    for i in range(len(matrix)):
        if matrix[i][i] == 0:
            for j in range(len(matrix[:, i])):
                if matrix[j][i] != 0:
                    matrix[i] += matrix[j]
                    break


def forward_gauss(matrix):
    for i in range(len(matrix)):
        for j in range(i + 1, len(matrix)):
            coeff = matrix[j][i] / matrix[i][i]
            matrix[j] -= matrix[i] * coeff


def backward_gauss(matrix):
    n = len(matrix)
    x = [0] * n
    for i in range(n - 1, -1, -1):
        x[i] = matrix[i][n] / matrix[i][i]
        for j in range(i):
            matrix[j][n] -= matrix[j][i] * x[i]
            matrix[j][i] = 0
    return x


matrix = np.column_stack((matrix, answers))
make_diagonal_dominant(matrix)
remove_zeros_from_diagonal(matrix)
make_diagonal_dominant(matrix)
forward_gauss(matrix)
x = backward_gauss(matrix)
print("Самостоятельное решение\n", x)


Решение, полученное с помощью библиотеки numpy
 [ 2.50000000e+00 -4.50000000e+00  9.47390314e-16 -4.50000000e+00
 -2.50000000e+00 -2.00000000e+00]
Самостоятельное решение
 [2.5, -4.5, -0.0, -4.5, -2.5, -2.0]
